version: '3'

services:
  db:
    build: ./docker/mysql
    platform: linux/x86_64
    container_name: db
    volumes:
      - ./docker/mysql/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=hoge
  api:
    image: golang:1.16.7
    tty: true
    volumes:
      - ./src:/go/src
    depends_on:
      - db
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    volumes:
      - ./doc/openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      - API_URL=openapi.yaml
    ports:
      - 8081:8080
