version: '3'

services:
  db:
    build: ./docker/mysql
    platform: linux/x86_64
    volumes:
      - ./docker/mysql/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=hoge
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "root", "-phoge", "-h", "localhost"]
      interval: 1s
      retries: 30
  api:
    image: golang:1.16.7
    tty: true
    volumes:
      - .:/go/src
    depends_on:
      db:
        condition: service_healthy
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    volumes:
      - ./docs/openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      - API_URL=openapi.yaml
    ports:
      - 8081:8080
