// Code generated by MockGen. DO NOT EDIT.
// Source: app/domain/repository/item_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kenta4327/example-of-ec-site/app/domain/model"
)

// MockItemRepository is a mock of ItemRepository interface.
type MockItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockItemRepositoryMockRecorder
}

// MockItemRepositoryMockRecorder is the mock recorder for MockItemRepository.
type MockItemRepositoryMockRecorder struct {
	mock *MockItemRepository
}

// NewMockItemRepository creates a new mock instance.
func NewMockItemRepository(ctrl *gomock.Controller) *MockItemRepository {
	mock := &MockItemRepository{ctrl: ctrl}
	mock.recorder = &MockItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemRepository) EXPECT() *MockItemRepositoryMockRecorder {
	return m.recorder
}

// FindItem mocks base method.
func (m *MockItemRepository) FindItem(id int) model.ItemEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindItem", id)
	ret0, _ := ret[0].(model.ItemEntity)
	return ret0
}

// FindItem indicates an expected call of FindItem.
func (mr *MockItemRepositoryMockRecorder) FindItem(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindItem", reflect.TypeOf((*MockItemRepository)(nil).FindItem), id)
}
