@startuml administrator

left to right direction

actor システム管理者
rectangle 管理画面 {
    システム管理者 --> (商品情報を一覧で見る)
    システム管理者 --> (商品情報を検索する)
    システム管理者 --> (商品情報を登録する)
    システム管理者 --> (商品情報を更新する)
    システム管理者 --> (商品情報を削除する)
    システム管理者 --> (商品情報を一括登録する)
    システム管理者 --> (商品情報を一括更新する)
}

@enduml
