@startuml class

package presentation <<Rectangle>> {
    package api <<Rectangle>> {
        class router
    }
}

package test <<Rectangle>> {
    package mock <<Rectangle>> {
        class ItemRepositoryMock
    }
}

package infrastructure <<Rectangle>> {
    package db <<Rectangle>> {
        class ItemRepositoryDbMysql
    }
}

package application <<Rectangle>> {
    package usecase <<Rectangle>> {
        class BrowseItemUseCase
        class BrowseItemUseCaseTest
    }
    package dto <<Rectangle>> {
        class BrowseItemDto
    }
}

package domain <<Rectangle>> {
    package repository <<Rectangle>> {
        Interface ItemRepository
    }

    package model <<Rectangle>> {
        class ItemEntity
    }
}

api --> usecase
usecase --> repository
usecase --> model
usecase --> dto
db --|> repository
db --> model
mock --|> repository
mock --> model

@enduml