@startuml class

package presentation <<Rectangle>> {
    package api <<Rectangle>> {
        class router
    }
}

package test <<Rectangle>> {
    package usecase_test <<Rectangle>> {
        class BrowseItemUseCaseTest
    }
    package mock <<Rectangle>> {
        class ItemRepositoryMock
    }
}

package infrastructure <<Rectangle>> {
    package db <<Rectangle>> {
        class ItemRepositoryDbMysql
    }
}

package application <<Rectangle>> {
    package usecase <<Rectangle>> {
        class BrowseItemUseCase
    }
    package dto <<Rectangle>> {
        class BrowseItemDto
    }
}

package domain <<Rectangle>> {
    package repository <<Rectangle>> {
        Interface ItemRepository
    }

    package model <<Rectangle>> {
        class ItemEntity
    }
}

api --> usecase
db ---|> repository
db ---> model
usecase -> dto
usecase --> repository
usecase --> model

usecase_test -> mock
usecase_test --> usecase
usecase_test --> dto
mock ---|> repository
mock ---> model

@enduml